// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa2q9IsfVxUwAOKV5TeS-tL9XypNlCdoQ',
    appId: '1:714513387400:web:1f9518aecf2135cf31b43d',
    messagingSenderId: '714513387400',
    projectId: 'gundam-stock-app',
    authDomain: 'gundam-stock-app.firebaseapp.com',
    databaseURL: 'https://gundam-stock-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gundam-stock-app.firebasestorage.app',
    measurementId: 'G-K2RC05PTPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1jedZ1at3Y_KdAOvPKez0Gxg78dijq-s',
    appId: '1:714513387400:android:9c372cdb5605b48d31b43d',
    messagingSenderId: '714513387400',
    projectId: 'gundam-stock-app',
    databaseURL: 'https://gundam-stock-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gundam-stock-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyi7lW2F8gQzomj-xNFVBDXypgI6ah39g',
    appId: '1:714513387400:ios:3f50dbccb157f1e931b43d',
    messagingSenderId: '714513387400',
    projectId: 'gundam-stock-app',
    databaseURL: 'https://gundam-stock-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gundam-stock-app.firebasestorage.app',
    iosBundleId: 'com.example.gundamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyi7lW2F8gQzomj-xNFVBDXypgI6ah39g',
    appId: '1:714513387400:ios:3f50dbccb157f1e931b43d',
    messagingSenderId: '714513387400',
    projectId: 'gundam-stock-app',
    databaseURL: 'https://gundam-stock-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gundam-stock-app.firebasestorage.app',
    iosBundleId: 'com.example.gundamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa2q9IsfVxUwAOKV5TeS-tL9XypNlCdoQ',
    appId: '1:714513387400:web:c569b7902819400731b43d',
    messagingSenderId: '714513387400',
    projectId: 'gundam-stock-app',
    authDomain: 'gundam-stock-app.firebaseapp.com',
    databaseURL: 'https://gundam-stock-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gundam-stock-app.firebasestorage.app',
    measurementId: 'G-HKH713LGRR',
  );
}
